name: ci
on:
  push:
    branches:
      - master
      - dev
  pull_request:

env:
  DOCKER_IMAGE_TAG: ${{ github.ref == 'refs/heads/master' && 'prod-' || 'dev-' }}${{ github.sha }}
  GITHUB_REGISTRY: ghcr.io
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  build_image:
    permissions:
      id-token: write
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs: [ test ]
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Log in to the Container registry 
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image 🐳
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}