name: ci
on:
  push:
    branches:
      - master
      - dev
  pull_request:

env:
  DOCKER_IMAGE_TAG: ${{ github.ref == 'refs/heads/master' && 'prod-' || 'dev-' }}${{ github.sha }}
  GITHUB_REGISTRY: ghcr.io
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [ 18.x ]
  
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and test 
        run: |
          npm ci
          npm test

  build_image:
    permissions:
      id-token: write
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs: [ test ]
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Log in to the Container registry 
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image 🐳
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}
  
    scan_docker_image:
      permissions:
        id-token: read
        contents: read
        packages: read
      runs-on: ubuntu-latest
      needs: [ build_image ]
      steps:
        - name: Checkout 
          uses: actions/checkout@v2

        - name: Log in to the Container registry 
          uses: docker/login-action@v2
          with:
            registry: ${{ env.GITHUB_REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Scan Docker image 🐳
          uses: snyk/actions/docker@master
          continue-on-error: true
          with:
            image: ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}
            args: --file=Dockerfile --severity-threshold=high --sarif-file-output=snyk.sarif
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        - name: Upload Snyk report as sarif 
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: snyk.sarif